apiVersion: v1
kind: Secret
metadata:
    name: contact-api-secret
    namespace: portfolio
type: Opaque
stringData:
    BREVO_API_KEY: ENC[AES256_GCM,data:L5kUPt5J66miIK/zytJhi4cas476XUdbTYTm72Kiq4muYIRJ9+l+Az6+QNbZZb2NSgOH51/CIM9aZOCew6ZUyOutLTpLt544loGeDkoWCuNhKTjvH9yXdsk=,iv:TWEqQ44kVAT8hWYWg6rcTpK8k1WZs9iMcMX9JD1Z4pM=,tag:AgOUleKjzY8xQW7PuqImOg==,type:str]
    FROM_NAME: ENC[AES256_GCM,data:Lxlwon+lWamVVLBLEEI=,iv:aNexTOIMHlTekxBthSdcYqpPdUEYdYMoPle3VTF5MW4=,tag:CltQ5iMfarWf9BI2z4uJ3w==,type:str]
    FROM_EMAIL: ENC[AES256_GCM,data:vB+qtKYQj4jqP6rNJ8COjJlls6Q=,iv:vkoLOL9Ze5oblu3j0Tb7RSntonwC7riBs8ZST3p9TpA=,tag:KWTb8vURslNgKg7yFsZ1IQ==,type:str]
    TO_EMAIL: ENC[AES256_GCM,data:iUOpDP40SiEiK8hGuthE5HoL,iv:OP2tm0OiH6K4ioLbk2AoN9ec4cLQTlM5Gw0p16pXJRQ=,tag:CYG5Jl4TPIZqUYQcfKq+cA==,type:str]
    TO_NAME: ENC[AES256_GCM,data:EBbaglro1khbLz+fdko=,iv:0yaAZ0M0USxQKpeZLCzTCvr9Nb6sAyIdcvCGM2M0+6w=,tag:KqiCOWypN5oNKNiYfUJ99w==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:2670papRhtUffRUQpITpDtqLfi7sD2kSPl1atbkxiKyUvLk/v9Wnyk86eg==,iv:JpYx60gO9OWpoAWNPyUxQl79HVWZLHgIb2XwBGQMjNs=,tag:05UWg4dz5w8g84ZF2DIfgg==,type:str]
sops:
    age:
        - recipient: age1229yll8w7j8n4fmvahud4e76avdk3rd5jfzxuepuu7pa7jf3mgqqrq8ptt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeFhja3daUGRPSGc4djFI
            UUNuWjVSSkNvTDdTMDZLQXFHdE5nQnVFVmdFCk1qRVBxb2lxNkd5NjRXb3FXQW1F
            cnhhMWdEeGdVV0dmb1ZGRjZYRlVIRVkKLS0tIEVWVW9aME1IVm1PeTdnQ3lySnNS
            czhKSTNTZUE0RnN3L3E5QjdORnZOaVUKfjlZwG8GoNSQ5BJhjxieFXJBvluWTxP8
            uAn4Qj+iVozwsgjLzJX17vcF8JyODI+Jhpxy+eXBiRcD4YaC6/DypA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:33:56Z"
    mac: ENC[AES256_GCM,data:22Y7brhCDix7b3+88pnazaRqzxy5jZaGPDeL3qvnsDentBqu15D8pqRZ7mcqeyGYNJzILmR5EPw0w4mVifIg3fvhkImhxXxp5JAvsoafrp3eAP4XlxFap3Tu6WkBGYGbPymfIE8inRXfHeOCYWNarXoecxZypoVBMbvZQtfwBMM=,iv:yKW0WCZtIu36rcBrgQFvW6lAgY4SXjX1jy7RagNcXFg=,tag:U+RUQf+EBgzPgrrBiy7Oqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
